# Generated by Django 5.2.6 on 2025-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_location_image_alter_review_date_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='tag',
            field=models.CharField(choices=[('City Park', 'City Park'), ('State Park', 'State Park'), ('National Park', 'National Park'), ('Wildlife Refuge', 'Wildlife Refuge'), ('Zoo', 'Zoo'), ('Aviary', 'Aviary'), ('Other', 'Other')], default='City Park', help_text='(Include relevant bird species)', max_length=50),
        ),
    ]
