# Generated by Django 5.2.6 on 2025-09-17 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_location_birds_location_city_location_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='birds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
