# Generated by Django 5.2.6 on 2025-09-22 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_location_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='birds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='(Include relevant bird species)', size=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='tag',
            field=models.CharField(choices=[('City Park', 'City Park'), ('State Park', 'State Park'), ('National Park', 'National Park'), ('Wildlife Refuge', 'Wildlife Refuge'), ('Zoo', 'Zoo'), ('Aviary', 'Aviary'), ('Other', 'Other')], default='City Park', max_length=50),
        ),
    ]
