# Generated by Django 5.2.6 on 2025-09-22 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_location_birds_alter_location_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='birds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='(Include relevant bird species; separate them by comma)', size=None),
        ),
    ]
