# Generated by Django 5.2.6 on 2025-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_location_birds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.URLField(blank=True, help_text='(Please insert image URL)', null=True),
        ),
    ]
