# Generated by Django 5.2.6 on 2025-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.URLField(blank=True, help_text='(Please insert image URL of location)', null=True),
        ),
    ]
